### ISSUE TITLE
arubaoss_config module not working on ansible 2.10

### ISSUE THREAD

**Issue by craigers521** [aruba/aos-switch-ansible-collection#3]
I recently upgraded to ansible 2.10 and it seems the arubaoss_config module is having trouble importing some modules it needs to execute properly.  It appears the directory structure has changed a bit and its not looking in the right place.  Works fine on ansible 2.9.  

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 613, in _execute
    self._connection = self._get_connection(cvars, templar)
  File "/usr/local/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 908, in _get_connection
    connection, plugin_load_context = self._shared_loader_obj.connection_loader.get_with_context(
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 826, in get_with_context
    obj.__init__(instance, *args, **kwargs)
  File "/Users/cse015/.ansible/collections/ansible_collections/ansible/netcommon/plugins/connection/network_cli.py", line 354, in __init__
    self.cliconf = cliconf_loader.get(self._network_os, self)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 780, in get
    return self.get_with_context(name, *args, **kwargs).object
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 800, in get_with_context
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/loader.py", line 764, in _load_module_source
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/cse015/.ansible/collections/ansible_collections/arubanetworks/aos_switch/plugins/cliconf/arubaoss.py", line 26, in <module>
    from ansible.module_utils.network.common.utils import to_list # NOQA
ModuleNotFoundError: No module named 'ansible.module_utils.network'
fatal: [cab1tcsw1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
```

**Comment by hrv231** [comment]
Hello,

This is happening to me too, it is related to this ticket I opened with Ansible:
https://github.com/ansible/ansible/issues/72239

https://github.com/ansible/ansible/issues/72239#issuecomment-711160601

Please fix this for us.

Thank you Tiffany!

**Comment by tchiapuziowong** [comment]
Hi everyone! Yes we're working on the solution now and should have a fix uploaded soon - thank you for your patience!

**Comment by tchiapuziowong** [comment]
Just pushed a commit to fix this! Please install the latest version of the collection with the following command:
`ansible-galaxy collection install arubanetworks.aos_switch -f`
https://github.com/aruba/aos-switch-ansible-collection/commit/536f1da55796fd65107bdd46423e99e1d30718cb
